name: Discord PR Notifications
on: 
  pull_request:
    types: [ opened ]
jobs:
  notif:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notif
        run: 'curl -X POST -H "Content-Type: application/json" -d "$(<$GITHUB_EVENT_PATH)" 165.227.250.219:8081'